controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation



#Post Controller
post_index:
    path: /post
    controller: App\Controller\PostController::index

post_create:
    path: /post/create
    controller: App\Controller\PostController::create

post_show:
    path: /post/show/{id}
    controller: App\Controller\PostController::show

post_edit:
    path: /post/edit/{id}
    controller: App\Controller\PostController::edit

post_delete:
    path: /post/delete/{id}
    controller: App\Controller\PostController::destroy


#Home Controller
home_index:
    path: /
    controller: App\Controller\HomeController::index

home_price:
    path: /home/price
    controller: App\Controller\HomeController::price

home_about:
    path: /home/about
    controller: App\Controller\HomeController::about

home_contact:
    path: /home/contact
    controller: App\Controller\HomeController::contact

#MailController
mail_sendMail:
    path: /sendMail/{id}
    controller: App\Controller\MailController::sendMail

#LoginController
app_logout:
    path: /logout
    methods: GET
